default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>

development:
  <<: *default
  database: fire_alert_development

test:
  <<: *default
  database: fire_alert_test

production:
  <<: *default
  database: fire_alert_production
  username: fire_alert
  password: <%= ENV['FIRE_ALERT_DATABASE_PASSWORD'] %>
